<?xml version = "1.0" encoding = "UTF-8"?>
<?xml-stylesheet type = "text/css" href = "css/style.css"?>

<!DOCTYPE root [
    <!ELEMENT root (university+)>
    <!ELEMENT university (name, score, places, city)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT score (#PCDATA)>
    <!ELEMENT places (#PCDATA)>
    <!ELEMENT city (#PCDATA)>
]>

<root>
    <university>
        <name>БГТУ</name>
        <score>302</score>
        <places>230</places>
        <city>Минск</city>
    </university>
    <university>
        <name>БГУИР</name>
        <score>270</score>
        <places>454</places>
        <city>Минск</city>
    </university>
    <university>
        <name>БГУИР</name>
        <score>270</score>
        <places>454</places>
        <city>Минск</city>
    </university>
    <university>
        <name>БГУИР</name>
        <score>270</score>
        <places>454</places>
        <city>Минск</city>
    </university>
</root>